MVP CLI Proposal implementation: leaf and root interactions
vacp2p/zerokit pull request #167
Opened 2023-05-25 07:55 UTC by tyshko-rostyslav

Closes #157

2023-05-26 05:34 UTC, rymnc commented on rln-cli/src/main.rs
> +            let output_data = File::open(&file)?;
Can we just log to stdout here?

2023-05-26 05:36 UTC, rahulghangas requested changes

2023-05-26 11:24 UTC, tyshko-rostyslav commented on rln-cli/src/main.rs
> +                .ok_or(Report::msg("no RLN initialized"))?
Fixed

2023-05-26 11:24 UTC, tyshko-rostyslav commented on rln-cli/src/main.rs
> +                .ok_or(Report::msg("no RLN initialized"))?
Fixed

2023-05-26 11:25 UTC, tyshko-rostyslav commented on rln-cli/src/main.rs
> +                .ok_or(Report::msg("no RLN initialized"))?
Fixed

2023-05-26 11:33 UTC, tyshko-rostyslav commented on rln-cli/src/main.rs
> +            let output_data = File::open(&file)?;
Redirected the output

2023-05-26 11:48 UTC, rymnc approved these changes
LGTM, thanks
for the future prs, let all the outputs be directed to stdout
we should also consider working on documentation for it too.

2023-05-26 14:21 UTC, curryrasul approved these changes
LGTM too!

2023-05-29 09:43 UTC, rahulghangas approved these changes

2023-05-29 13:19 UTC, merged