WIP: New implementations and tests for Zerokit v0.1
vacp2p/zerokit pull request #34
Opened 2022-08-22 17:59 UTC by s1fr0

Targets https://github.com/vacp2p/zerokit/issues/31

2022-08-24 15:41 UTC, richard-ramos approved these changes
:100: 

Looking at the code, a random idea i had that wanted to ask you about is:
What do you think of extracting in a patch file or separate branch these changes?:
- in poseidon_tree.rs:
```rs
//pub type PoseidonTree = FullMerkleTree<PoseidonHash>;
//pub type MerkleProof = FullMerkleProof<PoseidonHash>;
```
- the functions defined in `rln/src/utils.rs`. 

That way the source code would not contain commented code, and someone wanting to use either the FullMerkleTree, or the conversion utils could either cherry pick the commit from the branch, or apply the git patch  (assuming this operation is documented somewhere)

2022-08-24 18:50 UTC, richard-ramos commented
Sounds good! I did not know about rust features!

2022-09-13 05:55 UTC, oskarth requested changes
This is not a release PR, it is doing _a lot_ of things at once. These should be separate PRs. The release PR should be minimal and only about adding release notes etc.

See e.g. how this is done in nwaku: https://github.com/status-im/nwaku/pull/1075/files

I'm also not convinced that we should decrease the capability this library has as part of the first release.

2022-09-14 03:48 UTC, oskarth commented on multiplier/Cargo.toml
> -[package]
This is a useful example for onboarding and understanding roughly how things fit together. I don't think it makes sense to remove this package.

We could move it to an example directory.

2022-09-14 03:49 UTC, oskarth commented on poseidon-tornado/README.md
> -# Poseidon-Tornado wrapper
We want this soon, but I agree it is in a so-so state and better to base based on RLN from scratch at this point.

2022-09-14 03:51 UTC, oskarth commented on poseidon-tornado/README.md
> -# Poseidon-Tornado wrapper
Removed in https://github.com/vacp2p/zerokit/commit/1d8a5f59b60eea88cdd69d68df760ebb3ae73e54

cc @staheri14 if you want to see what this code is doing

2022-09-14 03:52 UTC, oskarth commented on rln/Cargo.toml
> -# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
Do this in a separate PR

2022-09-14 03:53 UTC, oskarth commented on rln/src/circuit.rs
> +    Bn254, Fq as ArkFq, Fq2 as ArkFq2, Fr as ArkFr, G1Affine as ArkG1Affine,
This a change in functionality or so, belongs in a separate PR targeting an issue. Not in a release PR...

2022-09-14 03:53 UTC, oskarth commented on rln/src/merkle_tree.rs
> -////////////////////////////////////////////////////////////
This shouldn't be removed, it is a regression

2022-09-14 03:54 UTC, oskarth commented on rln/src/poseidon_hash.rs
> +
This seems like another feature ??

2022-09-14 03:56 UTC, oskarth commented on semaphore/Cargo.toml
> -[package]
I think this is still useful, we aren't unlikely to want to use this in the feature. There are no problems to keep it in the code base as WIP, and when it gets prioritized to update it.

2022-09-14 03:57 UTC, oskarth commented
Yeah I think better to close this PR and start from scratch with feature PRs and refactor PRs and then a minimal release note PR. This is just a monster right now with many separate intentions.

2022-09-14 04:20 UTC, oskarth commented on rln/Cargo.toml
>  version = "0.1.0"
@richard-ramos @staheri14  of the changes in the `rln` crate, which of these are must haves from your POV? Both for normal integration (e.g. bugs found in nwaku and go-waku) as well as for the experimental wasm support?

Trying to figure out which things should be part of initial v0.1 release and which are OK to deal with later.

2022-09-16 23:59 UTC, closed without merging